### PR TITLE
Include jupyter notebook in sphinx doc

### PR DESCRIPTION
**Pull request by alixdamman**
- Tutorial includes some 0.19 features (title argument for ndrange, ... functions + xxx_by() functions).
- Extension 'nbsphinx' + package 'pandoc' required to generate the documentation (nbsphinx belongs to conda-forge channel). The documentation is generated as usual (make html).
- currently, nbsphinx do not allowed to produce latex documentation because of a bug in nbsphinx.

### CODE REVIEW

**Comment by alixdamman** [comment]
FYI : Problem with the generation of LaTeX documentation has been solved in version 0.2.12 of nbsphinx. I guess it will be soon available on conda (currently it's 0.2.11).

**Comment by gdementen** [comment]
I don't really get why pandoc is required...

**Comment by alixdamman** [comment]
Did you try to generate the doc without pandoc ?

**Comment by alixdamman** [comment]
What about "Read the Docs" to store the documentation somewhere?

**Comment by gdementen** [comment]
That's fine with me. I already use it for liam2, even though for liam2 it is much less important since the documentation is also hosted directly on the website.

**Comment by gdementen** [comment]
closing because the PR is obsolete (the tutorial notebook was included via another PR)

**Pull request closed without merging**
