### PR TITLE
renamed data.h5 to demography.h5 and updated example.py

### PR DESCRIPTION
**Pull request by siddhugolu**
Fixes [#481](https://github.com/liam2/larray/issues/481)

### CODE REVIEW

**Comment by alixdamman** [comment]
Our code is licensed under the GPLv3, you accept that your contributions will be released under that license, OK?

Could you also start your commit message by fix #481 ?

**Comment by gdementen** [comment]
@alixdamman if we apply this PR, the file path needs to be update in the editor too (until you do larray-project/larray-editor#101)

**Comment by alixdamman** [comment]
Yes, I know ;)

**Comment by siddhugolu** [comment]
@alixdamman No problem at all, I accept the license. Modified the commit message.

**Pull request merged**
