### PR TITLE
globalarrays

### PR DESCRIPTION
**Pull request by gdementen**

### CODE REVIEW

**Comment by gdementen** [comment]
Yes, we probably should, I just don't know how to name it :)

**Comment by alixdamman** [comment]
all_arrays()?

**Comment by alixdamman** [comment]
Can I rebase and merge or do you to add something to this PR?

**Comment by gdementen** [comment]
In fact I was waiting for you to merge your approved PR so that I have to resolve the conflict instead of you since you were first. But if you want to merge this first, be my guest ;-)

**Pull request merged**
