### PR TITLE
fromstring

### PR DESCRIPTION
**Pull request by gdementen**

### CODE REVIEW

**Comment by alixdamman** [comment]
Have you tested what happened if one row contains more columns than expected ?
A user could write ,, somewhere by mistake.

**Comment by gdementen** [comment]
No, I did not test that, but I think it's fine to fail in that case as long as the error message is clear, which is probably not the case.

**Comment by gdementen** [comment]
rebased on current master

**Comment by gdementen** [comment]
could be squashed though

**Comment by alixdamman** [comment]
Thanks

**Comment by gdementen** [comment]
hmmm, I just realize this is severly broken... it obviously (when looking at the code) creates a string array not an integer array like one would expect!

**Pull request merged**
