### PR TITLE
Fix(#580): Renamed sheet_name to sheet in to_excel

### PR DESCRIPTION
**Pull request by Avasse**
I renamed every "sheet_name" to "sheet" in to_excel def.

### CODE REVIEW

**Comment by alixdamman** [comment]
@Avasse Some unittests failed. Looks like you tried a simple Find/Replace and changed the name of an internal function you shouldn't have ;)

**Comment by alixdamman** [comment]
@Avasse This change also need a changelog (see doc/source/changes/version_0_28.rst.inc), section "Miscellaneous improvements"

**Comment by gdementen** [comment]
A few comments: 
* your proposed change does not work yet, as demonstrated by the failure of Travis CI (the red cross above). You could click on "details" to see why it failed. No worries, but you need to fix this before we can accept the change.
* we cannot simply rename an argument without providing some kind of compatibility layer for our existing users. Please use the deprecate_kwarg decorator. Search in the code for "deprecate_kwarg" for examples on how to use it.
* you need to provide a changelog entry in doc/source/changes/version_0_28.rst.inc
* you need to state somewhere (in the commit message or here) that you accept your contribution to be released under the terms of the GPLv3 license. If you could also include in your message "and all future contributions" that would make things easier if you contribute more in the future.
@alixdamman : we need to update our how to contribute page...

**Comment by Avasse** [comment]
Alright thanks for your replies, i'm on it !

**Pull request closed without merging**
